name: Deploy to Firebase Hosting on PR

on: workflow_dispatch

jobs:
  runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn install

      - name: Make build
        run: CI= yarn build

      - name: Deploy to Firebase
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting
          env:
            FIREBASE_TOKEN: "${{ secrets.FIREBASE_TOKEN }}"